export const DATABASE_CONNECTION_NAME = 'DATABASE_CONNECTION';

export const DATABASE_MODULE_NAME = 'DatabaseModule';

export const DATABASE_RETRY_ATTEMPTS = 5;

export const DATABASE_RETRY_DELAY = 3000;

export const DATABASE_CONNECTION_TIMEOUT = 10000;

export const DATABASE_SERVER_SELECTION_TIMEOUT = 5000;